### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/tic-tac-toe#1]
- First
  - [x] Deploy to surge instead of github pages
  - [x] Better build scripts
  - [x] Fix travis ci
  - [x] Deploy _only_ when tests passes
  - [ ] Make it responsive
- Second (pwa)
  - [x] Cache assets
  - [x] Cache initial state
  - [x] Cache data from network
  - [x] Install banners

**Comment by YerkoPalma** [comment]
Try to use [on-load](https://github.com/shama/on-load) to register service worker
